[project]
name = "manim-kor"
version = "0.1.0"
description = "Imcommit manim projects"
readme = "README.md"
requires-python = "==3.11.7"
dependencies = [
    "manim==0.19.0",
    "raenim",
]

[tool.uv.sources]
raenim = { git = "https://github.com/CodingVillainKor/raenim.git" }
